# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxswiftMvvmSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxswiftMvvmSample

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'PKHUD', '~> 5.0'
  pod "Himotoki", "~> 3.1"

  target 'RxswiftMvvmSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxswiftMvvmSampleUITests' do
    # Pods for testing
  end

end
